### ISSUE TITLE
Add support for MessageDecorator

### ISSUE THREAD

**Issue by deonvdv** [EventSaucePHP/LaravelEventSauce#10]
Since `AggregateRootRepository->repository()` is private, it cannot be overridden in the Aggregate Repository, meaning we cannot add `MessageDecoratorChain` as 4th parameter to ConstructingAggregateRootRepository. https://eventsauce.io/docs/advanced/message-decoration/

Could you add support for `MessageDecorator` or make `AggregateRootRepository->repository()` public?

Or maybe there is another way?

Thanks

**Comment by driesvints** [comment]
Yeah, that was definitely still on my list to look into. Appreciating a PR if you could whip one up because I probably don't have time to look into this soon. Thanks!

**Comment by deonvdv** [comment]
Added PR #11 - ready for review @driesvints

**Comment by deonvdv** [comment]
@driesvints - can you pls merge PR #11 ?

**Comment by driesvints** [comment]
Hey @deonvdv. I gave some feedback on the PR which I'd like you to take care of first before reviewing. Thanks.

**Comment by frankdejonge** [comment]
implemented on main
