### ISSUE TITLE
[IDEA] Migration generation command instead of migration

### ISSUE THREAD

**Issue by frankdejonge** [EventSaucePHP/LaravelEventSauce#2]
I currently see a migration in this code. A common strategy is to use one table per aggregate type. This could be facilitated by having a command that generates the schema instead of having the migration. This way you don't have to double allocate.

Thoughts?

**Comment by driesvints** [comment]
Ah, didn't know that. Is it really that common? Haven't seen that anywhere yet.

**Comment by driesvints** [comment]
What are the general benefits besides separation of events?

**Comment by frankdejonge** [comment]
It's quite common in the workplace. There's a number of benefits:

- Easier to move later on (no splitting).
- Easier to re-publish historical streams without filtering.
- Smaller indexes (better performance).
- Isolation.
- Easier inspection.
- Can be configured for their own needs.
- Can be moved to different servers if needed.

On the other hand, not spitting it has no real benefit other than "fewer tables" which is not an actual benefit, it may just be a preference.

**Comment by driesvints** [comment]
@frankdejonge I'll take a thorough look later on to see how we might do this.

**Comment by sandervanhooft** [comment]
> On the other hand, not spitting it has no real benefit other than "fewer tables" which is not an actual benefit, it may just be a preference.

I'm new to event sourcing, but if I'd like to list all user activity across multiple aggregates, wouldn't this be easier with a single event store table?

**Edit**: Scratch the above. I dived a bit deeper into the material and it indeed is considered best practice to split event stores by aggregate.

**Comment by driesvints** [comment]
I've implemented this currently but am still thinking of keeping one single table the default. Thoughts?

**Comment by sandervanhooft** [comment]
I think keeping the single table by default is the easiest to get started event sourcing.

**Comment by driesvints** [comment]
Yeah same here. Just wondering if @frankdejonge has really objections against it. Willing to switch over the default if so.

**Comment by frankdejonge** [comment]
I’d still advocate for using one table per aggregate type. Not per aggregate btw. To me it’s just like how entities that have identical structures don’t share a table, this to me is the same. I wouldn’t go as far as some other tools go and make one table per aggregate (so dynamic amount of tables). But in the end there’s nothing stopping people from going in either direction.

**Comment by driesvints** [comment]
@frankdejonge okay. I'll revise this on Saturday to swap the default 👍 

In the meantime, does anyone have a good article which explains the reasoning behind this in detail? Would be good to link to that in the docs so people know the reasoning behind it. Thanks! :)

**Comment by frankdejonge** [comment]
I’ll add a section in the main docs for this.

**Comment by frankdejonge** [comment]
I wrote this: https://eventsauce.io/docs/advanced/database-structure/

**Comment by driesvints** [comment]
@frankdejonge nice! Some thoughts: 

- Change table name in first example to `domain_messages`. This is also used in other examples in EventSauce
- Remove the `Table per aggregate identifier.` example. I don't think it's even worth documenting this use case and should be discouraged.

**Comment by frankdejonge** [comment]
Given that the table per aggregate identifier is something that's not uncommon, albeit very specialized, I'm going to leave it. It doesn't hurt to include it and people should make up their own mind.

**Comment by frankdejonge** [comment]
BTW, feel free to PR any clarifications.

**Comment by driesvints** [comment]
@frankdejonge will do!

**Comment by driesvints** [comment]
The make command will now scaffold a migration per aggregate root type by default. The default migration is still included if people want to publish and use that.

**Comment by frankdejonge** [comment]
I'm liking how this turned out! 👍
