### ISSUE TITLE
Add rationale/motivation note

### ISSUE THREAD

**Issue by rawtaz** [EventSaucePHP/LaravelEventSauce#21]
Given that the (referenced in the README file) library at https://spatie.be/docs/laravel-event-sourcing/v4/introduction already exists, an obvious question when visiting this repository is "Why another one of these libraries for Laravel?".

It would be great if someone could add an explanation of why this one came into existence given the previously mentioned one (that seems mature enough), what it brings and what makes it unique.

**Comment by driesvints** [comment]
This one is a direct adapter for the EventSauce library while the one mentioned above is a complete standalone package for Laravel.
