### ISSUE TITLE
recorded_at invalid MySQL format

### ISSUE THREAD

**Issue by sandervanhooft** [EventSaucePHP/LaravelEventSauce#25]
When using the default migration, I'm getting the following exception when trying to persist an event:

`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2021-03-23 20:49:02.932458+0000' for column 'recorded_at' at row 1`

Which seems strange to me because the default migration is actually using:

```php
$table->dateTime('recorded_at', 6)->index();
$table->dateTimeTz('recorded_at', 6)->index(); // also tried this
```

I've digged around the code of LaravelEventSauce and the core php EventSauce package, and I'm not sure what is causing this.

Any pointers where to start debugging this?

mysql  Ver 8.0.23
Laravel v8.33.1
Eventsauce 0.8.2
laravel-eventsauce 0.3.1

**Comment by driesvints** [comment]
From the looks at it it's using a different serialization for the dates. This reminds me to an update we did back in Laravel 7: https://laravel.com/docs/7.x/upgrade#date-serialization

I don't know why this would suddenly break for you. Did something change in EventSauce. The persistence of the message happens here: https://github.com/EventSaucePHP/LaravelEventSauce/blob/20fb71323b86feb9162c9310ed51802222ddb9cd/src/LaravelMessageRepository.php#L50

So it seems to me that `$headers[Header::TIME_OF_RECORDING]` now has a different value all of the sudden? Can you maybe dive into EventSauce and check what type of value this is? Sorry, I'm a bit too busy atm myself to check.

**Comment by sandervanhooft** [comment]
Thanks @driesvints ! That helped me narrow down the problem, not sure yet about the solution.

It works if I update the line you mentioned from

```php
'recorded_at' => $headers[Header::TIME_OF_RECORDING],
```

to

```php
'recorded_at' => \Illuminate\Support\Str::of($headers[Header::TIME_OF_RECORDING])->before('+0000'),
```

**Comment by sandervanhooft** [comment]
The format is defined here in PointInTime: 

https://github.com/EventSaucePHP/EventSauce/blob/16334aad3ad8e3a510b2d4e235a7541ca463c044/src/PointInTime.php#L11-L14

The suffix `+0000` is there by design. This is a mismatch with the `datetime` field in the Laravel migration.

**Comment by sandervanhooft** [comment]
I am using a fairly default Laravel / MySQL setup. MySQL 8.0, InnoDB schema.

In terms of the table structure there seems to be no difference between using `datetime` and `datetimeTz` in the migration. This may be causing the format / table structure mismatch.

```php
$table->bigIncrements('id');
$table->string('event_id', 36);
$table->string('event_type', 100);
$table->string('event_stream', 36)->index();
$table->dateTime('recorded_at', 6)->index();
$table->dateTimeTz('recorded_at_with_timezone', 6)->nullable(); // Expected different field format here
$table->text('payload');
```

results in

```SQL
CREATE TABLE `domain_messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_stream` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `recorded_at` datetime(6) NOT NULL,
  `recorded_at_with_timezone` datetime(6) DEFAULT NULL, # No difference
  `payload` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `domain_messages_event_stream_index` (`event_stream`),
  KEY `domain_messages_recorded_at_index` (`recorded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by driesvints** [comment]
This has always worked afaik. So something must have changed. I don't have any time atm to look into this unfortunately...

In general I believe `dateTimeTz` shouldn't be needed because the value should be stored as UTC.

**Comment by sandervanhooft** [comment]
Thanks Dries!

It took some googling but it seems to be a known EventSauce / MySQL 8 issue: https://github.com/EventSaucePHP/EventSauce/issues/108

There seems to be plans to fix this on the v1.0 release 🤞

**Comment by sandervanhooft** [comment]
For now I've overridden the `AggregateRootRepository` provided by this package so I could inject my own `HeaderDecorator` - as a workaround it's sufficient.

```php
<?php

namespace Support\EventSauce;

use EventSauce\EventSourcing\Header;
use EventSauce\EventSourcing\Message;
use EventSauce\EventSourcing\MessageDecorator;
use Illuminate\Support\Str;

class Mysql8MessageDecorator implements MessageDecorator
{
    public function decorate(Message $message): Message
    {
        return $message->withHeader(
            Header::TIME_OF_RECORDING,
            Str::of($message->header(Header::TIME_OF_RECORDING))->before('+0000')
        );
    }
}
```

I don't see an easy way to inject MessageDecorators without a BC. This may be something to keep in mind for a v1.

**Comment by driesvints** [comment]
I should set up a build which runs the test suite against MySQL v8 rather than sqlite 🤔

**Comment by sandervanhooft** [comment]
Good thinking. That's exactly what I ran into. SQLite all green, MySQL (8) all red.

**Comment by driesvints** [comment]
Hey Sander. Looks like a solution is indeed coming in EventSauce v1.0 which will change quite a few things. I'm going to close this one for now since you found a workaround in pre-v1.0

**Comment by sandervanhooft** [comment]
Sure thing. Thanks so far!
