### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by driesvints** [EventSaucePHP/LaravelEventSauce#28]
Hey all,

I'm looking for someone that can take over maintenance of Laravel EventSauce from me as I want to clear some time up for other things I'm working on. Also want to thank @frankdejonge for the trust he gave me in the past years 🙌 

If you're interested, feel free to reply to this issue.

**Comment by rahmanii0** [comment]
Iam ready to do it, it's kind of an awesome experience ✌️

**Comment by driesvints** [comment]
Thanks for your interest @rahmanii0! Have you ever worked with this library or Event Sourcing before?

**Comment by rahmanii0** [comment]
i did , i've used it in my laravel's projects  @driesvints

**Comment by frankdejonge** [comment]
Hi all,

First of all I'd like to thank @driesvints for his time and energy he has put in to help the project. I'd love to get some Laravel specific help for the framework. I'll take on the immediate responsibilities for this package in terms of governance and can work with aspiring maintainers to build up some confidence over time and work toward getting access to the repository.

**Comment by Parables** [comment]
@frankdejonge @driesvints Still looking for maintainers? 

This issue is closed but looking at the [last commit](https://github.com/EventSaucePHP/LaravelEventSauce/commit/2ef8253b2d105b9da8458272187f46ed8b924a10), it looks pretty abandoned to me. 

Love to help out

**Comment by kirkbushell** [comment]
I'd be happy to help out here, if you'd have me? We're currently working on implementing EventSauce into our legacy project, working heavily with DDD and I'd be willing to work on this, make changes updates and fixes as we continue to utilise this library.
