### ISSUE TITLE
Make it easier to use Laravel's default TestCase

### ISSUE THREAD

**Issue by freekmurze** [EventSaucePHP/LaravelEventSauce#5]
By default Laravel comes with a default `Illuminate\Foundation\Testing\TestCase` which has a lot of niceties to test Laravel apps. EventSauce comes with a `AggregateRootTestCase` base class to test commands and events. 

It would be nice if we had a way to use all the methods of both Laravel's and EventSauces test cases.

**Comment by sandervanhooft** [comment]
I'm thinking about two ways to achieve this:

1) An `AssertsEventSauce` trait
2) Let the LaravelEventSauce `AggregateRootTestCase` extend the `Illuminate\Foundation\Testing\TestCase`

After tinkering a bit with the first I must say I'm leaning towards the second now. The `AggregateRootTestCase` would always be a superset of the `Illuminate\Foundation\Testing\TestCase` for this package.

**Comment by sandervanhooft** [comment]
Alternatively we could publish a `AggregateRootTestCase` to the default Laravel `tests/` folder root to keep things flexible.

**Comment by driesvints** [comment]
Hey @sandervanhooft. I'll try to have a look at this on Wednesday.

**Comment by driesvints** [comment]
Hey @sandervanhooft. I've looked into this but the more I think it over, the more I believe we shouldn't add this to the package. AggregateRoots should always be tested in isolation without any outside dependencies. That's why I can't think of a reason why we would need this.

Are there any reasons why you thought this would be useful. @freekmurze same for you: anything you can think of why and how you'd use this?

**Comment by sandervanhooft** [comment]
Hi @driesvints ,

I understand your scoping concern - testing AggregateRoots etc is not the same as testing Laravel app stuff / framework bindings.

But one of the selling points of EventSauce is the robust and easy set of test tools it comes with. I wouldn't consider using it without a decent test suite. Wrapping your head around the event sourcing paradigm is one thing, but figuring out appropriate test mechanisms on your own would really hamper adoption imho.

The EventSauce test tools unfortunately do not work with this Laravel package out of the box.

I am convinced there's a need for these test tools, I'm just not sure this PR is the way to go.

**Comment by driesvints** [comment]
@sandervanhooft hmm, I don't really agree sorry. I haven't run into a case where I needed any of the Laravel testing tools for my aggregate root test cases. They're not using any outside dependencies and should be testable with just everything the EventSauce class brings to you. 

It would greatly help if you could show some examples on how you'd use these so we can go back and forth a bit to see what the best solution for those cases are.

Maybe @frankdejonge can weigh in a bit as well here?

**Comment by freekmurze** [comment]
I agree that having to extend another testclass feels a bit "foreign" in a the test suite of a Laravel app. Having a trait `MakesAggregateAssertions` would feel nicer.  Haven't looked into if it's technically possible in a clean way though.

**Comment by driesvints** [comment]
@freekmurze @sandervanhooft the thing is that I'm genuinely looking for use cases for when you'd need anything from Laravel's test case when testing aggregate roots. I really believe there aren't any use cases but feel free to prove me wrong :)

**Comment by frankdejonge** [comment]
Perhaps the discussion would be more meaningful if we go into more concrete examples. I'm inclined to lean in the direction @driesvints suggests, but I'm not sure what problems @sandervanhooft is actually facing. Sander, could you explain what you're running into? There's more than one way to solve a problem and I'd like so see if we can help you out. If the concern is only theoretical, or the fact that a different base test case is extended is the only concern, then I don't feel it's a problem. But I have the feeling there might be something more at play here.

**Comment by sandervanhooft** [comment]
@frankdejonge agreed.

I was running into some signature clashes, can't remember which ones now. Will look into this, may take a few days.

**Comment by driesvints** [comment]
@sandervanhooft no worries, feel free to reply when you can 👍

**Comment by driesvints** [comment]
Hey all. Since it's been a few days I'm going to go ahead and close this. @sandervanhooft feel free to reply here with any extra thoughts you might have and we could look into it further then.
